apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: krateo-snowplow
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/krateo/krateo-snowplow
    version: "1.0.47"
