apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: krateo-snowplow-agent
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/krateo/krateo-snowplow-agent
    version: "0.1.0"
